#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

./packages/Allwclean
./lib/Allwclean
./solver/Allwclean

# ----------------------------------------------------------------- end-of-file
