#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean libso thermophysicalModels/combustionModels
wclean libso thermophysicalModels/radiation/submodels/absorptionEmissionModel
#wclean libso thermophysicalModels/solidChemistryModel_2.2.x
wclean libso fvPatchFields
wclean libso fvPatchFieldsPyrolysis
wclean libso rtiProbes
wclean libso splashingModels
wclean libso injectionModels
wclean libso additionalCloudFunctionObjects
wclean libso regionCoupling
wclean libso regionModels/pyrolysisModels

# ----------------------------------------------------------------- end-of-file
